/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_agora_rawdata_MediaPreProcessing */

#ifndef _Included_io_agora_rawdata_MediaPreProcessing
#define _Included_io_agora_rawdata_MediaPreProcessing
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Java_io_agora_rawdata_MediaPreProcessing
 * Method:    setCallback
 */
JNIEXPORT void JNICALL Java_io_agora_rawdata_MediaPreProcessing_setCallback
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
